In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
train  = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/startupdata/training_set_label.csv" )
test = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/startupdata/testing_set_label.csv')

In [ ]:
train.shape,test.shape

((923, 48), (231, 47))

In [ ]:
train.head()

   Unnamed: 0 state_code   latitude  ...  avg_participants is_top500    status
0        1005         CA  42.358880  ...            1.0000         0  acquired
1         204         CA  37.238916  ...            4.7500         1  acquired
2        1001         CA  32.901049  ...            4.0000         1  acquired
3         738         CA  37.320309  ...            3.3333         1  acquired
4        1002         CA  37.779281  ...            1.0000         1    closed

[5 rows x 48 columns]

In [ ]:
train=train.drop(['Unnamed: 0','id','Unnamed: 6','name'],axis=1)
test=test.drop(['Unnamed: 0','id','Unnamed: 6','name'],axis=1)

In [ ]:
combine=train.append(test)
combine.reset_index(inplace=True)
combine.head()

   index state_code   latitude  ...  avg_participants is_top500    status
0      0         CA  42.358880  ...            1.0000         0  acquired
1      1         CA  37.238916  ...            4.7500         1  acquired
2      2         CA  32.901049  ...            4.0000         1  acquired
3      3         CA  37.320309  ...            3.3333         1  acquired
4      4         CA  37.779281  ...            1.0000         1    closed

[5 rows x 45 columns]

In [ ]:
closedat=[]
for i in combine['closed_at']:
  if len(str(i))==3:
    closedat.append(0)
  else:
    closedat.append(1)
combine['is_closed']=closedat

In [ ]:
combine.head()

   index state_code   latitude  ...  is_top500    status is_closed
0      0         CA  42.358880  ...          0  acquired         0
1      1         CA  37.238916  ...          1  acquired         0
2      2         CA  32.901049  ...          1  acquired         0
3      3         CA  37.320309  ...          1  acquired         0
4      4         CA  37.779281  ...          1    closed         1

[5 rows x 46 columns]

CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
MA MA
CA CA
CA CA
CA CA
KY KY
NY NY
CO CO
VA VA
CA CA
CA CA
NY NY
CA CA
TX TX
WA WA
CA CA
CA CA
CO CO
IL IL
CA CA
CA CA
TX TX
CA CA
CA CA
WA WA
NC NC
CA CA
PA PA
NY NY
CA CA
CA CA
CA CA
NY NY
GA GA
NH NH
CA CA
WA WA
CA CA
CA CA
NY NY
MA MA
CA CA
CA CA
CA CA
MA MA
TX TX
MA MA
CA CA
CA CA
CA CA
CA CA
CA CA
MO MO
MA MA
CA CA
WA WA
FL FL
MA MA
CA CA
WA WA
CO CO
CA CA
CA CA
CA CA
CA CA
FL FL
CA CA
TX TX
CA CA
CA CA
CA CA
NY NY
MA MA
CA CA
NJ NJ
CO CO
CA CA
NY NY
WV WV
CA CA
MI MI
CA CA
WA WA
CA CA
DC DC
CA CA
CA CA
NY NY
CA CA
IL IL
NJ NJ
CA CA
CA CA
GA GA
WA WA
WA WA
CA CA
CA CA
VA VA
VA VA
IL IL
CA CA
CT CT
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
NC NC
NY NY
NY NY
MA MA
CA CA
TX TX
NY NY
CA CA
MA MA
MD MD
PA PA
VA VA
CA CA
NY NY
IL IL
CA CA
CA CA
OH OH
GA GA
CA CA
MA MA
CA CA
CA CA
CA CA
CA CA
NY NY
CA CA
VA VA
CA CA
CA CA
NY NY
CA CA
CA CA
GA GA
CA CA
CA CA
CA CA
CA CA
CA CA
IL IL
MA MA
CA CA
VA VA
WA WA
CO CO
IL IL
CA CA
CA CA
TX TX
CA CA
TN TN
NY NY
CA CA
NY NY
NY NY
MA MA
MN MN
CA CA
TX TX
WA WA
CA CA
PA PA
MA MA
CA CA
TX TX
CO CO
CA CA
NY NY
CA CA
IL IL
CA CA
CA CA
CA CA
MA MA
CA CA
CA CA
CA CA
CA CA
CA CA
MA MA
CA CA
PA PA
CA CA
CA CA
IL IL
NC NC
PA PA
CA CA
CA CA
CA CA
CA CA
CA CA
TX TX
MA MA
CA CA
CA CA
GA GA
NY NY
CA CA
CA CA
CA CA
CA CA
NY NY
RI RI
DC DC
CA CA
CA CA
CA CA
WA WA
CA CA
NY NY
CA CA
CA CA
TX TX
CA CA
TX TX
CA CA
CA CA
MI MI
CA CA
IL IL
NY NY
PA PA
CA CA
CA CA
MA MA
MA MA
CA CA
TX TX
WA WA
MD MD
OR OR
NY NY
PA PA
NY NY
MA MA
CA CA
CO CO
GA GA
CA CA
RI RI
CA CA
CA CA
MA MA
MA MA
CA CA
UT UT
TX TX
CA CA
TX TX
CA CA
CA CA
CA CA
MA MA
WA WA
CA CA
CA CA
CA CA
NC NC
NY NY
CA CA
CA CA
MA MA
FL FL
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
MD MD
CA CA
WA WA
MA MA
WA WA
MA MA
MA MA
MD MD
CA CA
TX TX
CA CA
NY NY
CA CA
CA CA
CA CA
ME ME
NY NY
CA CA
NY NY
CA CA
CA CA
CA CA
CA CA
WA WA
WA WA
NY NY
CA CA
CO CO
CA CA
NY NY
CA CA
GA GA
CA CA
CA CA
PA PA
CA CA
CA CA
CA CA
IL IL
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
NY NY
NY NY
CA CA
CA CA
MA MA
TX TX
CA CA
CA CA
NY NY
CA CA
NY NY
CA CA
TX TX
MI MI
VA VA
NJ NJ
PA PA
CA CA
CA CA
NY NY
MN MN
MA MA
CA CA
NC NC
CA CA
NY NY
CA CA
WA WA
TX TX
NY NY
CA CA
CA CA
MA MA
NY NY
MA MA
MA MA
NY NY
CA CA
CA CA
WA WA
CA CA
CA CA
MA MA
NY NY
CA CA
CA CA
CA CA
CA CA
NY NY
CA CA
MA MA
CA CA
MA MA
NV NV
MA MA
VA VA
CA CA
CA CA
CA CA
CA CA
NY NY
CA CA
CA CA
MA MA
CA CA
WA WA
NY NY
CA CA
CA CA
NY NY
NY NY
CA CA
MA MA
CA CA
CA CA
TX TX
IL IL
NY NY
CA CA
NY NY
NY NY
CA CA
MA MA
CA CA
NY NY
WA WA
CA CA
CO CO
CA CA
CA CA
OR OR
NY NY
MA MA
TX TX
CA CA
CT CT
CO CO
WA WA
MD MD
NY NY
CA CA
TX TX
CA CA
CA CA
NY NY
CA CA
CA CA
IL IL
MA MA
MA MA
CA CA
MA MA
CA CA
CA CA
FL FL
NY NY
CA CA
CA CA
CA CA
NY NY
NY NY
WA WA
CA CA
CA CA
CA CA
CA CA
CA CA
TX TX
CA CA
CA CA
NY NY
OH OH
MA MA
CA CA
OH OH
CA CA
CA CA
CA CA
MA MA
TX TX
UT UT
CA CA
NM NM
NJ NJ
CA CA
MA MA
CA CA
PA PA
CA CA
CA CA
MO MO
CA CA
CA CA
CA CA
NY NY
NY NY
TX TX
NY NY
PA PA
CA CA
IN IN
MA MA
CA CA
CA CA
CA CA
PA PA
CO CO
CA CA
CA CA
NY NY
CA CA
CA CA
CA CA
TX TX
CA CA
CO CO
NY NY
CA CA
CA nan
CA CA
CA CA
CA CA
IL IL
NY NY
CA CA
PA PA
CA CA
TN TN
CA CA
NY NY
MA MA
CA CA
TN TN
CA CA
WA WA
CA CA
CA CA
MA MA
CA CA
WA WA
CA CA
CA CA
CA CA
CA CA
MD MD
CA CA
CA CA
WA WA
CA CA
CA CA
CA CA
CO CO
MA MA
CA CA
CA CA
CA CA
NY NY
CA CA
CA CA
MA MA
CA CA
NY NY
GA GA
CA CA
CA CA
MA MA
CA CA
CA CA
NY NY
KY KY
CA CA
VA VA
CA CA
MA MA
CA CA
CA CA
VA VA
OR OR
NY NY
PA PA
ME ME
CA CA
TX TX
CA CA
MA MA
CA CA
CA CA
MA MA
GA GA
NJ NJ
NY NY
MD MD
CA CA
CA CA
CA CA
TX TX
CA CA
CA CA
CA CA
DC DC
NY NY
CA CA
MA MA
NV NV
CA CA
NY NY
CA CA
TX TX
CA CA
MA MA
CA CA
MN MN
CA CA
CA CA
CA CA
CA CA
NY NY
CA CA
CA CA
CA CA
CA CA
WA WA
CA CA
MA MA
MA MA
CA CA
CA CA
NY NY
CA CA
CT CT
CA CA
NY NY
NY NY
CA CA
NY NY
CA CA
CA CA
WA WA
CA CA
TX TX
CO CO
CA CA
CA CA
CA CA
FL FL
MA MA
NH NH
CA CA
CA CA
CA CA
CO CO
WA WA
CA CA
MN MN
PA PA
CA CA
CA CA
MA MA
CA CA
CA CA
CA CA
IL IL
CA CA
MN MN
NC NC
MA MA
WA WA
MA MA
MA MA
CA CA
CA CA
NY NY
CA CA
NY NY
WA WA
CA CA
CA CA
MA MA
NC NC
CA CA
MA MA
CA CA
CA CA
MA MA
NY NY
IL IL
MA MA
CA CA
NY NY
CA CA
NY NY
NY NY
NY NY
IL IL
TX TX
CA CA
CA CA
CA CA
CA CA
CA CA
TX TX
NY NY
CA CA
CA CA
TX TX
DC DC
MA MA
CA CA
CA CA
MA MA
CA CA
GA GA
CA CA
CA CA
CA CA
VA VA
TX TX
CA CA
NJ NJ
VA VA
GA GA
CA CA
CA CA
TX TX
CA CA
AZ AZ
MA MA
OR OR
MA MA
CA CA
CA CA
CA CA
CA CA
MA MA
NY NY
WA WA
CA CA
NY NY
WA WA
PA PA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
NY NY
CA CA
NY NY
CA CA
OR OR
CA CA
MA MA
CA CA
NY NY
CA CA
CA CA
CA CA
CA CA
CA CA
TX TX
CA CA
CA CA
CA CA
TX TX
CA CA
NY NY
CA CA
CA CA
NY NY
NY NY
OH OH
IN IN
MA MA
CA CA
CA CA
CA CA
CA CA
PA PA
WA WA
CA CA
CA CA
UT UT
CA CA
NY NY
NY NY
CA CA
OH OH
CA CA
OR OR
CA CA
WA WA
CA CA
CA CA
CA CA
NY NY
CO CO
CA CA
CA CA
CA CA
CA CA
CA CA
WA WA
CA CA
CA CA
NY NY
CA CA
CA CA
CA CA
CA CA
NY NY
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
WA WA
WA WA
MA MA
TX TX
CA CA
MA MA
AZ AZ
CA CA
CA CA
OH OH
WA WA
CA CA
CA CA
NY NY
CA CA
TX TX
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
FL FL
CT CT
WA WA
CA CA
WA WA
RI RI
NY NY
MA MA
CA CA
CA CA
CO CO
IL IL
CA CA
CA CA
NY NY
CA CA
CA CA
TX TX
CA CA
CA CA
NJ NJ
ID ID
CA CA
CA CA
CA CA
CA CA
MA MA
CA CA
MA MA
CA CA
CA CA
CA CA
NY NY
MA MA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
TX TX
CA CA
VA VA
CO CO
CA CA
CA CA
OR OR
CA CA
CA CA
CA CA
AR AR
NY NY
MA MA
MA MA
NY NY
CA CA
IL IL
NY NY
CO CO
CA CA
CA CA
CA CA
TX TX
CA CA
CA CA
CA CA
CA CA
CA CA
NY NY
CA CA
CA CA
TX TX
NY NY
WI WI
NY NY
WA WA
CA CA
MA MA
CA CA
CA CA
CA CA
CT CT
CA CA
NJ NJ
CA CA
CA CA
CA CA
VA VA
CA CA
CA CA
CA CA
CA CA
CA CA
WA WA
CA CA
CA CA
ME ME
CA CA
MA MA
TX TX
UT UT
WA WA
CA CA
CA CA
CA CA
CA CA
UT UT
CA CA
CA CA
NY NY
MA MA
CA CA
CA CA
CA CA
WA WA
CA CA
NY NY
CA CA
CA CA
NC NC
CA CA
WA WA
CA CA
CA CA
MA MA
CO CO
CA CA
CA CA
CO CO
MA MA
MO MO
CA CA
CA CA
CA CA
CA CA
UT UT
UT UT
TX TX
CA CA
CA CA
CA CA
CA CA
CA CA
MA MA
CA CA
WA WA
WA WA
CA CA
CA CA
CA CA
CA CA
CA CA
MA MA
CA CA
WA WA
CA CA
FL FL
CT CT
CA CA
CA CA
CA CA
CA CA
NY NY
PA PA
AZ AZ
CA CA
CA CA
CA CA
MA MA
MA MA
WA WA
CA CA
CA CA
CA CA
PA PA
NY NY
CA CA
VA VA
CA CA
TX TX
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
PA PA
CA CA
CA CA
CA CA
CA CA
CA CA
WA WA
MA MA
PA PA
CA CA
CA CA
TX TX
CA CA
CA CA
CT CT
CA CA
CA CA
TX TX
NY NY
CA CA
CA CA
CA CA
PA PA
VA VA
CA CA
WA WA
NY NY
CA CA
CA CA
WA WA
WA WA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
VA VA
NE NE
MA MA
UT UT
CA CA
CA CA
CA CA
NJ NJ
CA CA
CA CA
WA WA
NY NY
MA MA
NY NY
CA CA
NY NY
CA CA
VA VA
CA CA
CA CA
FL FL
CA CA
CA CA
MA MA
CA CA
CA CA
CA CA
CA CA
FL FL
CA CA
CA CA
CO CO
NY NY
CO CO
CA CA
NY NY
CO CO
WA WA
CA CA
CA CA
MA MA
IL IL
CA CA
TX TX
MA MA
OR OR
CA CA
CA CA
CT CT
CA CA
CA CA
GA GA
MA MA
CA CA
WI WI
CA CA
CA CA
CT CT
MA MA
RI RI
MA MA
CA CA
CA CA
VA VA
CA CA
IA IA
CA CA
CA CA
CA CA
CA CA
CA CA
FL FL
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
CA CA
OR OR
CA CA
CA CA
NY NY
NY NY

In [ ]:
combine.drop(['state_code.1','index'],axis=1,inplace=True)

In [ ]:
combine.isna().sum()

index                         0
state_code                    0
latitude                      0
longitude                     0
zip_code                      0
city                          0
founded_at                    0
closed_at                   735
first_funding_at              0
last_funding_at               0
age_first_funding_year        0
age_last_funding_year         0
age_first_milestone_year    195
age_last_milestone_year     195
relationships                 0
funding_rounds                0
funding_total_usd             0
milestones                    0
state_code.1                  1
is_CA                         0
is_NY                         0
is_MA                         0
is_TX                         0
is_otherstate                 0
category_code                 0
is_software                   0
is_web                        0
is_mobile                     0
is_enterprise                 0
is_advertising                0
is_gamesvideo                 0
is_ecommerce                  0
is_biotech                    0
is_consulting                 0
is_othercategory              0
object_id                     0
has_VC                        0
has_angel                     0
has_roundA                    0
has_roundB                    0
has_roundC                    0
has_roundD                    0
avg_participants              0
is_top500                     0
status                      231
is_closed                     0
dtype: int64